### PR TITLE
All Paladins champions loading screen art

### PR DESCRIPTION
**Pull request by terzom**
I've extracted all Paladin champion screen loading portraits from the Official game files and added them in the asset folder in a new folder called "champion-loading-portraits".

Also a short Readme to help me or others to extract new upcoming champions.

I kept the original naming of files and folder, saw no point in renaming them all.

### CODE REVIEW

**Comment by Likqez** [comment]
LGTM! I will have to check the images and get back to you.

**Comment by Likqez** [comment]
Merged.

### A suggestion for someone who wants to spend time and put effort into this:

Parsing each image to its respective SkinID😄 
Maybe providing a json dictionary or replacing the filenames with the ids instead.

**Comment by luissilva1044894** [comment]
@terzom Thanks for the PR! I'll really appreciate it! ❤️

**Comment by luissilva1044894** [comment]
Now some imgs are returned by the endpoint. I've request Aaron to add them in the JSON, but idk...

URL are: <https://hirez-api.onrender.com/paladins/skins/{champ_id}-{skin_id2}.png>

https://hirez-api.onrender.com/paladins/skins/2417-19316.png

**Pull request merged**
